[package]
name = "async-callable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
async_fn_traits = "0.1.1"
paste = "1.0.14"
